apiVersion: v1
kind: Pod
metadata:
  name: downward-api-env-demo
spec:
  containers:
    - name: main-container
      image: busybox:1.36  # 使用一个轻量级镜像用于演示
      # 这个启动命令会打印我们注入的环境变量，然后保持运行
      command: ["sh", "-c", "echo '正在运行的Pod名称是: $(MY_POD_NAME)'; echo '所属的命名空间是: $(MY_POD_NAMESPACE)'; echo 'Pod的IP地址是: $(MY_POD_IP)'; sleep 3600"]
      env:
        # 定义第一个环境变量 MY_POD_NAME
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              # apiVersion 是必需的, 对于Pod字段通常是 v1
              apiVersion: v1
              # fieldPath 指向Pod对象中的具体字段路径
              fieldPath: metadata.name
        # 定义第二个环境变量 MY_POD_NAMESPACE
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        # 定义第三个环境变量 MY_POD_IP
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
  restartPolicy: Never # 方便演示，执行完命令后Pod不会自动重启
